### ISSUE TITLE
format to fluka has a  list index bug

### ISSUE THREAD

**Issue by py1sl** [esl-lewis/neutronics_tool#4]
i used dates 2015 1 1 to 2016 1 1 and the fluka output file throws a list index error with line 129 which in my version is
irrprofi = str("IRRPROFI"+(20 - (len(str(countdays[x]))+9))*" "
                           +str(countdays[x])+"."+(10-len(str(flux[x])))*" "
                           +str(flux[x])+(9-len(str(countdays[x+1])))*" "
                           +str(countdays[x+1])+"."+(10-len(str(flux[x+1])))*" "
                           +str(flux[x+1])+(9-len(str(countdays[x+2])))*" "
                           +str(countdays[x+2]) +"."+(10-len(str(flux[x+2])))*" "
                           +str(flux[x+2])+"\n")

**Comment by esl-lewis** [comment]
Using len function and counting from a loop gave different totals which led to an indexing error. Has been fixed. Further testing would be better.
