### ISSUE TITLE
must be a better way for valid date checking

### ISSUE THREAD

**Issue by py1sl** [esl-lewis/neutronics_tool#5]
the user input date read part does a couple of checks but there are many cases it does not check for
 e.g. 

- only adding a year and no month or year.  

- months with days other than 31

- dates in the future 

- dates before the data

im sure this is a problem that has been solved and rather than reinvent the wheel find the solution.  incidentally pandas datetime part does check if its a valid month etc, this might be part of the solution

**Comment by esl-lewis** [comment]
Updated to check for valid year-month-day formatting. For dates in the future and before the data, does not throw an error but plots empty data. Will be remedied to warn user.

**Comment by esl-lewis** [comment]
Added warnings for dates in the future or before data collection began
